'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';

const apps=[['▦','System'],['▱','Files'],['⌁','Web'],['◇','Code'],['▧','Notes'],['◉','Focus'],['⌘','Terminal'],['⚙','Settings']];
const rows=['1234567890-=','QWERTYUIOP[]','ASDFGHJKL;\'','ZXCVBNM,./'];
const help=['help       show available commands','date       current system time','status     network and system status','clear      clear terminal output','whoami     current operator','apps       list installed modules'];

export default function Home(){
 const [boot,setBoot]=useState(true); const [clock,setClock]=useState('00:00:00'); const [tab,setTab]=useState('MAIN'); const [input,setInput]=useState(''); const [history,setHistory]=useState<string[]>(['Windows PowerShell','Copyright (C) DEV UI Corporation. All rights reserved.','',"Type 'help' to initialize command registry.",'']); const inputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const bootTimer=setTimeout(()=>setBoot(false),1800);const tick=()=>setClock(new Date().toLocaleTimeString('en-GB'));tick();const timer=setInterval(tick,1000);return()=>{clearTimeout(bootTimer);clearInterval(timer)}},[]);
 const run=(event?:FormEvent)=>{event?.preventDefault();const command=input.trim().toLowerCase();if(!command)return;let output:string[]=[];if(command==='help')output=help;else if(command==='date')output=[new Date().toString()];else if(command==='status')output=['NETWORK: ONLINE  |  SIGNAL: 97%  |  LATENCY: 18ms','CORE: STABLE     |  MEMORY: 42%  |  STORAGE: 36%'];else if(command==='whoami')output=['operator@dev-ui'];else if(command==='apps')output=[apps.map(a=>a[1]).join('  /  ')];else if(command==='clear'){setHistory([]);setInput('');return}else output=[`Command not found: ${command}`,'Type help for available commands.'];setHistory(lines=>[...lines,`PS C:\\Users\\Operator> ${input}`,...output,'']);setInput('')};
 const key=(value:string)=>{if(value==='BACK')setInput(v=>v.slice(0,-1));else if(value==='ENTER')run();else if(value==='SPACE')setInput(v=>v+' ');else setInput(v=>v+value.toLowerCase());inputRef.current?.focus()};
 if(boot)return <main className="boot"><div className="boot-logo"><span>ↄ</span>DEV UI<small>SYSTEM INTERFACE</small></div><div className="boot-line"><i/></div><p>INITIALIZING SECURE WORKSPACE...</p></main>;
 return <main className="os-shell" onClick={()=>inputRef.current?.focus()}>
  <div className="scanlines"/><header className="sysbar"><span>DEV UI // CORE SYSTEM</span><b>SESSION 01</b><span>SECURE CHANNEL · ONLINE</span></header>
  <aside className="left-hud"><section><small>LOCAL TIME</small><strong>{clock}</strong><p>2026 / 08 / 26</p></section><section><small>SYSTEM</small><div className="stat"><span>CPU</span><i><b style={{width:'32%'}}/></i><em>32%</em></div><div className="stat"><span>RAM</span><i><b style={{width:'46%'}}/></i><em>46%</em></div><div className="stat"><span>SSD</span><i><b style={{width:'68%'}}/></i><em>68%</em></div></section><section className="coordinates"><small>LOCATION</small><p>31.9539° N</p><p>35.9106° E</p></section></aside>
  <section className="terminal"><nav>{['MAIN','DATA_01','DATA_02','DATA_03','DATA_04'].map(t=><button className={tab===t?'selected':''} onClick={e=>{e.stopPropagation();setTab(t)}} key={t}>{t}</button>)}</nav><div className="terminal-body">{tab==='MAIN'?<><div className="terminal-scroll">{history.map((line,i)=><p key={`${i}-${line}`}>{line||'\u00a0'}</p>)}</div><form onSubmit={run}><label>PS C:\Users\Operator&gt;</label><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} autoFocus spellCheck={false}/><span className="cursor"/></form></>:<div className="empty-module"><span>◈</span><p>{tab} MODULE READY</p><small>NO ACTIVE PROCESS</small></div>}</div></section>
  <aside className="right-hud"><section><small>NETWORK STATUS</small><div className="net"><span>STATE</span><b>ONLINE</b></div><div className="net"><span>UP/DOWN</span><b>86 / 24 MB</b></div><div className="net"><span>PING</span><b>18 MS</b></div></section><section><small>WORLD VIEW</small><div className="globe"><i/><i/><i/><b>+</b></div><p>ENDPOINT: AMMAN</p></section><section><small>NETWORK TRAFFIC</small><div className="traffic">{[30,52,36,72,46,83,64,42,78,58,91,68].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div></section></aside>
  <div className="bottom-zone"><section className="app-dock">{apps.map(([icon,label])=><button key={label} onClick={e=>{e.stopPropagation();setHistory(h=>[...h,`Launching ${label} module...`,'']);setTab('MAIN')}}><span>{icon}</span><small>{label}</small></button>)}</section><section className="keyboard"><div className="key-row function"><button onClick={()=>key('ESC')}>ESC</button>{['F1','F2','F3','F4','F5','F6','F7','F8','F9','F10'].map(k=><button key={k}>{k}</button>)}</div>{rows.map((row,index)=><div className="key-row" key={row}>{index===1&&<button className="wide">TAB</button>}{index===2&&<button className="wide">CAPS</button>}{index===3&&<button className="wide">SHIFT</button>}{row.split('').map(k=><button key={k} onClick={()=>key(k)}>{k}</button>)}{index===0&&<button className="wide" onClick={()=>key('BACK')}>BACK</button>}{index===1&&<button className="enter" onClick={()=>key('ENTER')}>ENTER</button>}</div>)}<div className="key-row last"><button>CTRL</button><button>FN</button><button className="space" onClick={()=>key('SPACE')}/><button>ALT GR</button><button>CTRL</button><button>◁</button><button>▽</button><button>▷</button></div></section></div>
  <footer><span>DEV UI BUILD 4.6.2</span><span>ALL SYSTEMS NOMINAL</span><span>OPERATOR / NEZAR</span></footer>
 </main>
}

