'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';

type AppId='terminal'|'files'|'notes'|'focus'|'calculator'|'settings'|'monitor'|'web';
type Note={id:number;title:string;body:string;updated:string};
type FileItem={id:number;name:string;type:string;size:string};
const apps:{icon:string;label:string;id:AppId}[]=[{icon:'▦',label:'Monitor',id:'monitor'},{icon:'▱',label:'Files',id:'files'},{icon:'⌁',label:'Web',id:'web'},{icon:'◇',label:'Calc',id:'calculator'},{icon:'▧',label:'Notes',id:'notes'},{icon:'◉',label:'Focus',id:'focus'},{icon:'⌘',label:'Terminal',id:'terminal'},{icon:'⚙',label:'Settings',id:'settings'}];
const rows=['1234567890-=','QWERTYUIOP[]','ASDFGHJKL;\'','ZXCVBNM,./'];
const defaultNotes:Note[]=[{id:1,title:'DEV UI roadmap',body:'Connect modules, refine animations, and ship the public build.',updated:'Today 19:40'},{id:2,title:'Command ideas',body:'Add search, export, theme, and system diagnostics commands.',updated:'Today 18:12'}];
const defaultFiles:FileItem[]=[{id:1,name:'project-brief.txt',type:'TXT',size:'4 KB'},{id:2,name:'system-map.json',type:'JSON',size:'12 KB'},{id:3,name:'interface-spec.md',type:'MD',size:'8 KB'}];

export default function Home(){
 const [boot,setBoot]=useState(true),[clock,setClock]=useState('00:00:00'),[activeApp,setActiveApp]=useState<AppId>('terminal'),[input,setInput]=useState(''),[history,setHistory]=useState<string[]>(['Windows PowerShell','Copyright (C) DEV UI Corporation. All rights reserved.','',"Type 'help' to initialize command registry.",'']);
 const [notes,setNotes]=useState<Note[]>(defaultNotes),[selectedNote,setSelectedNote]=useState(1),[files,setFiles]=useState<FileItem[]>(defaultFiles),[query,setQuery]=useState(''),[focusSeconds,setFocusSeconds]=useState(25*60),[focusRunning,setFocusRunning]=useState(false),[calc,setCalc]=useState(''),[accent,setAccent]=useState('cyan'),[scanlines,setScanlines]=useState(true);
 const inputRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const savedNotes=localStorage.getItem('devui-notes'),savedFiles=localStorage.getItem('devui-files'),savedAccent=localStorage.getItem('devui-accent');if(savedNotes)setNotes(JSON.parse(savedNotes));if(savedFiles)setFiles(JSON.parse(savedFiles));if(savedAccent)setAccent(savedAccent);const bt=setTimeout(()=>setBoot(false),1500);const tick=()=>setClock(new Date().toLocaleTimeString('en-GB'));tick();const timer=setInterval(tick,1000);return()=>{clearTimeout(bt);clearInterval(timer)}},[]);
 useEffect(()=>{localStorage.setItem('devui-notes',JSON.stringify(notes))},[notes]);useEffect(()=>{localStorage.setItem('devui-files',JSON.stringify(files))},[files]);useEffect(()=>{localStorage.setItem('devui-accent',accent)},[accent]);
 useEffect(()=>{if(!focusRunning)return;const t=setInterval(()=>setFocusSeconds(s=>{if(s<=1){setFocusRunning(false);return 0}return s-1}),1000);return()=>clearInterval(t)},[focusRunning]);
 const openApp=(id:AppId)=>{setActiveApp(id);if(id==='terminal')setTimeout(()=>inputRef.current?.focus(),20)};
 const run=(event?:FormEvent)=>{event?.preventDefault();const raw=input.trim(),command=raw.toLowerCase();if(!command)return;let output:string[]=[];const open=command.match(/^open\s+(\w+)/);if(command==='help')output=['help | date | status | whoami | apps | clear','open files | notes | focus | calculator | settings | monitor','echo [text] | search [term] | theme cyan|green|amber'];else if(command==='date')output=[new Date().toString()];else if(command==='status')output=['NETWORK: ONLINE  |  SIGNAL: 97%  |  LATENCY: 18ms','CORE: STABLE     |  MEMORY: 42%  |  STORAGE: 36%'];else if(command==='whoami')output=['operator@dev-ui'];else if(command==='apps')output=[apps.map(a=>a.label).join('  /  ')];else if(command.startsWith('echo '))output=[raw.slice(5)];else if(command.startsWith('search ')){setQuery(raw.slice(7));openApp('files');output=[`Searching local workspace for: ${raw.slice(7)}`] }else if(command.startsWith('theme ')){const c=command.slice(6);if(['cyan','green','amber'].includes(c)){setAccent(c);output=[`Accent theme changed to ${c}`]}else output=['Available themes: cyan, green, amber']}else if(open){const found=apps.find(a=>a.id===open[1]||a.label.toLowerCase()===open[1]);if(found){openApp(found.id);output=[`Opening ${found.label} module...`]}else output=['Module not found. Type apps to list modules.']}else if(command==='clear'){setHistory([]);setInput('');return}else output=[`Command not found: ${command}`,'Type help for available commands.'];setHistory(lines=>[...lines,`PS C:\\Users\\Operator> ${raw}`,...output,'']);setInput('')};
 const key=(v:string)=>{if(v==='BACK')setInput(x=>x.slice(0,-1));else if(v==='ENTER')run();else if(v==='SPACE')setInput(x=>x+' ');else setInput(x=>x+v.toLowerCase());inputRef.current?.focus()};
 const addNote=()=>{const id=Date.now();setNotes(n=>[{id,title:'Untitled note',body:'Start typing...',updated:'Just now'},...n]);setSelectedNote(id)};const currentNote=notes.find(n=>n.id===selectedNote)??notes[0];const updateNote=(patch:Partial<Note>)=>setNotes(n=>n.map(x=>x.id===currentNote?.id?{...x,...patch,updated:'Just now'}:x));
 const addFile=()=>{const id=Date.now();setFiles(f=>[{id,name:`new-file-${f.length+1}.txt`,type:'TXT',size:'0 KB'},...f])};
 const calculate=()=>{try{if(!/^[0-9+\-*/().\s]+$/.test(calc))throw new Error();const value=Function(`"use strict";return (${calc})`)();setCalc(String(value))}catch{setCalc('ERROR')}};
 if(boot)return <main className="boot"><div className="boot-logo"><span>ↄ</span>DEV UI<small>SYSTEM INTERFACE</small></div><div className="boot-line"><i/></div><p>INITIALIZING SECURE WORKSPACE...</p></main>;
 const appTitle=apps.find(a=>a.id===activeApp)?.label.toUpperCase();
 return <main className={`os-shell theme-${accent}`} onClick={()=>activeApp==='terminal'&&inputRef.current?.focus()}>{scanlines&&<div className="scanlines"/>}<header className="sysbar"><span>DEV UI // CORE SYSTEM</span><b>{appTitle} MODULE</b><span>SECURE CHANNEL · ONLINE</span></header>
  <aside className="left-hud"><section><small>LOCAL TIME</small><strong>{clock}</strong><p>2026 / 08 / 26</p></section><section><small>SYSTEM</small>{[['CPU','32%'],['RAM','46%'],['SSD','68%']].map(([a,b])=><div className="stat" key={a}><span>{a}</span><i><b style={{width:b}}/></i><em>{b}</em></div>)}</section><section className="coordinates"><small>LOCATION</small><p>31.9539° N</p><p>35.9106° E</p></section></aside>
  <section className="terminal module-window"><nav>{['MAIN','DATA_01','DATA_02','DATA_03','DATA_04'].map((t,i)=><button className={i===0?'selected':''} key={t}>{i===0?appTitle:t}</button>)}</nav><div className="terminal-body">{activeApp==='terminal'&&<><div className="terminal-scroll">{history.map((line,i)=><p key={`${i}-${line}`}>{line||'\u00a0'}</p>)}</div><form onSubmit={run}><label>PS C:\Users\Operator&gt;</label><input ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} autoFocus spellCheck={false}/><span className="cursor"/></form></>}
   {activeApp==='files'&&<div className="app-view files-view"><div className="app-toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search workspace..."/></label><button onClick={addFile}>+ NEW FILE</button></div><div className="file-grid">{files.filter(f=>f.name.toLowerCase().includes(query.toLowerCase())).map(f=><button key={f.id}><span>{f.type}</span><b>{f.name}</b><small>{f.size} · LOCAL</small></button>)}</div></div>}
   {activeApp==='notes'&&<div className="app-view notes-view"><aside><button className="new-note" onClick={addNote}>+ NEW NOTE</button>{notes.map(n=><button className={selectedNote===n.id?'active':''} onClick={()=>setSelectedNote(n.id)} key={n.id}><b>{n.title}</b><small>{n.updated}</small></button>)}</aside>{currentNote&&<article><input value={currentNote.title} onChange={e=>updateNote({title:e.target.value})}/><textarea value={currentNote.body} onChange={e=>updateNote({body:e.target.value})}/><footer><span>AUTO-SAVED LOCALLY</span><button onClick={()=>setNotes(n=>n.filter(x=>x.id!==currentNote.id))}>DELETE</button></footer></article>}</div>}
   {activeApp==='focus'&&<div className="app-view focus-view"><div className={focusRunning?'focus-core running':'focus-core'}><strong>{String(Math.floor(focusSeconds/60)).padStart(2,'0')}:{String(focusSeconds%60).padStart(2,'0')}</strong><small>{focusRunning?'SESSION ACTIVE':'READY TO FOCUS'}</small></div><div className="focus-controls"><button onClick={()=>setFocusRunning(r=>!r)}>{focusRunning?'PAUSE':'START'}</button><button onClick={()=>{setFocusRunning(false);setFocusSeconds(25*60)}}>RESET</button><button onClick={()=>setFocusSeconds(50*60)}>50 MIN</button></div></div>}
   {activeApp==='calculator'&&<div className="app-view calc-view"><input value={calc} onChange={e=>setCalc(e.target.value)} onKeyDown={e=>e.key==='Enter'&&calculate()} placeholder="0"/><div>{['7','8','9','/','4','5','6','*','1','2','3','-','0','.','C','+'].map(k=><button key={k} onClick={()=>k==='C'?setCalc(''):setCalc(v=>v+k)}>{k}</button>)}</div><button className="equals" onClick={calculate}>= EXECUTE</button></div>}
   {activeApp==='settings'&&<div className="app-view settings-view"><h2>INTERFACE SETTINGS</h2><section><span>ACCENT CHANNEL</span><div>{['cyan','green','amber'].map(c=><button className={accent===c?'active':''} onClick={()=>setAccent(c)} key={c}>{c.toUpperCase()}</button>)}</div></section><section><span>SCANLINE OVERLAY</span><button onClick={()=>setScanlines(v=>!v)}>{scanlines?'ENABLED':'DISABLED'}</button></section><section><span>LOCAL DATA</span><button onClick={()=>{setNotes(defaultNotes);setFiles(defaultFiles)}}>RESET WORKSPACE</button></section></div>}
   {activeApp==='monitor'&&<div className="app-view monitor-view">{[['CPU LOAD',32],['MEMORY BANK',46],['STORAGE',68],['NETWORK',78]].map(([n,v])=><section key={String(n)}><div><span>{n}</span><b>{v}%</b></div><i><em style={{width:`${v}%`}}/></i></section>)}<div className="monitor-log"><p>[OK] Core engine operational</p><p>[OK] Local storage mounted</p><p>[OK] Secure network online</p><p>[OK] All modules responding</p></div></div>}
   {activeApp==='web'&&<div className="app-view web-view"><div className="web-bar">⌁ https://dev.local/start</div><div><span>DEV</span><h2>LOCAL NETWORK PORTAL</h2><p>Secure browsing module is connected.</p><button onClick={()=>openApp('terminal')}>RETURN TO TERMINAL</button></div></div>}
  </div></section>
  <aside className="right-hud"><section><small>NETWORK STATUS</small>{[['STATE','ONLINE'],['UP/DOWN','86 / 24 MB'],['PING','18 MS']].map(x=><div className="net" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</section><section><small>WORLD VIEW</small><div className="globe"><i/><i/><i/><b>+</b></div><p>ENDPOINT: AMMAN</p></section><section><small>NETWORK TRAFFIC</small><div className="traffic">{[30,52,36,72,46,83,64,42,78,58,91,68].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div></section></aside>
  <div className="bottom-zone"><section className="app-dock">{apps.map(a=><button className={activeApp===a.id?'active':''} key={a.id} onClick={e=>{e.stopPropagation();openApp(a.id)}}><span>{a.icon}</span><small>{a.label}</small></button>)}</section>{activeApp==='terminal'?<section className="keyboard"><div className="key-row function"><button>ESC</button>{['F1','F2','F3','F4','F5','F6','F7','F8','F9','F10'].map(k=><button key={k}>{k}</button>)}</div>{rows.map((row,index)=><div className="key-row" key={row}>{index===1&&<button className="wide">TAB</button>}{index===2&&<button className="wide">CAPS</button>}{index===3&&<button className="wide">SHIFT</button>}{row.split('').map(k=><button key={k} onClick={()=>key(k)}>{k}</button>)}{index===0&&<button className="wide" onClick={()=>key('BACK')}>BACK</button>}{index===1&&<button className="enter" onClick={()=>key('ENTER')}>ENTER</button>}</div>)}<div className="key-row last"><button>CTRL</button><button>FN</button><button className="space" onClick={()=>key('SPACE')}/><button>ALT GR</button><button>CTRL</button><button>◁</button><button>▽</button><button>▷</button></div></section>:<section className="module-info"><span>{apps.find(a=>a.id===activeApp)?.icon}</span><h3>{appTitle}</h3><p>MODULE ACTIVE</p><button onClick={()=>openApp('terminal')}>⌘ OPEN TERMINAL</button></section>}</div>
  <footer><span>DEV UI BUILD 5.0.0</span><span>ALL SYSTEMS NOMINAL</span><span>OPERATOR / NEZAR</span></footer></main>
}

