'use client';
import { useEffect, useState } from 'react';

const navItems = [{icon:'⌂',label:'الرئيسية'},{icon:'▤',label:'ملاحظاتي'},{icon:'✓',label:'المهام'},{icon:'▱',label:'الملفات'},{icon:'◫',label:'التقويم'}];
const initialTasks = [{id:1,title:'مراجعة خطة المشروع',time:'10:00',done:true},{id:2,title:'ترتيب ملفات العمل',time:'12:30',done:false},{id:3,title:'كتابة أفكار الأسبوع',time:'15:00',done:false}];

export default function Home(){
 const [time,setTime]=useState(''); const [active,setActive]=useState('الرئيسية'); const [tasks,setTasks]=useState(initialTasks); const [focusMinutes,setFocusMinutes]=useState(25);
 useEffect(()=>{const update=()=>setTime(new Intl.DateTimeFormat('ar-JO',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date()));update();const timer=setInterval(update,1000);fetch('/api/tasks').then(r=>r.ok?r.json():null).then(data=>{if(data?.tasks?.length)setTasks(data.tasks.map((task:{id:number;title:string;time:string;done:number|boolean})=>({...task,done:Boolean(task.done)})))}).catch(()=>{});return()=>clearInterval(timer)},[]);
 const toggleTask=(id:number)=>setTasks(items=>items.map(task=>{if(task.id!==id)return task;const updated={...task,done:!task.done};fetch('/api/tasks',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,done:updated.done})}).catch(()=>{});return updated}));
 return <main className="workspace" dir="rtl"><div className="grid-glow" />
  <aside className="sidebar"><div className="brand"><span className="brand-mark">N</span><span>NOVA</span></div><nav aria-label="التنقل الرئيسي">{navItems.map(item=><button key={item.label} className={active===item.label?'nav-item active':'nav-item'} onClick={()=>setActive(item.label)}><span>{item.icon}</span><b>{item.label}</b></button>)}</nav>
   <div className="system-card"><div className="system-head"><span>حالة النظام</span><i /></div><div className="meter"><span>التخزين</span><b>36%</b></div><div className="bar"><i style={{width:'36%'}} /></div><div className="meter"><span>مساحة العمل</span><b>72%</b></div><div className="bar"><i style={{width:'72%'}} /></div></div>
   <button className="profile"><span className="avatar">ن</span><span><b>نزار</b><small>مساحة شخصية</small></span><i>•••</i></button></aside>
  <section className="content"><header className="topbar"><div><p className="eyebrow">مساحة العمل / {active}</p><h1>مساء الخير، نزار <span>✦</span></h1></div><div className="top-actions"><label className="search"><span>⌕</span><input aria-label="بحث" placeholder="ابحث في كل شيء..." /></label><button className="icon-btn" aria-label="الإشعارات">♧<i /></button><button className="new-btn">＋ إنشاء جديد</button></div></header>
   <div className="status-row"><article className="time-card panel"><p>الوقت المحلي <span>ASIA / AMMAN</span></p><strong dir="ltr">{time||'00:00:00'}</strong><small>الأربعاء، 26 آب 2026</small><div className="signal"><i/><i/><i/><i/></div></article><article className="quote-card panel"><span className="spark">✦</span><div><p>بداية هادئة، إنجازات أكبر.</p><small>لديك 3 مهام مجدولة لليوم</small></div><button>عرض اليوم ←</button></article><article className="weather-card panel"><div className="weather-icon">◒</div><div><strong>27°</strong><p>عمّان، الأردن</p></div><small>سماء صافية<br/>الرطوبة 31%</small></article></div>
   <div className="main-grid"><section className="panel tasks-panel"><div className="panel-title"><div><p className="eyebrow">TODAY / 03</p><h2>مهام اليوم</h2></div><button>عرض الكل ←</button></div><div className="task-list">{tasks.map(task=><button key={task.id} className={task.done?'task done':'task'} onClick={()=>toggleTask(task.id)}><span className="check">{task.done?'✓':''}</span><b>{task.title}</b><time>{task.time}</time><i>⋮</i></button>)}</div><button className="add-task">＋ أضف مهمة جديدة</button></section>
    <section className="panel notes-panel"><div className="panel-title"><div><p className="eyebrow">RECENT / NOTES</p><h2>ملاحظات سريعة</h2></div><button>فتح الملاحظات ←</button></div><div className="note-grid"><button className="note cyan"><span>أفكار المشروع</span><p>واجهة أبسط، اختصارات أسرع، وتركيز أكبر على تجربة المستخدم...</p><small>منذ 18 دقيقة</small></button><button className="note violet"><span>قائمة القراءة</span><p>التفكير العميق، بناء العادات، وتصميم الأنظمة...</p><small>أمس، 9:42 م</small></button><button className="note empty"><strong>＋</strong><span>ملاحظة جديدة</span></button></div></section>
    <section className="panel files-panel"><div className="panel-title"><div><p className="eyebrow">FILES / RECENT</p><h2>آخر الملفات</h2></div><button>كل الملفات ←</button></div><div className="file"><span className="file-icon pink">PDF</span><div><b>خطة العمل 2026</b><small>2.4 MB · منذ ساعتين</small></div><i>⋮</i></div><div className="file"><span className="file-icon blue">DOC</span><div><b>ملاحظات الاجتماع</b><small>840 KB · أمس</small></div><i>⋮</i></div><div className="file"><span className="file-icon green">XLS</span><div><b>متابعة المصروفات</b><small>1.1 MB · 24 آب</small></div><i>⋮</i></div></section>
    <section className="panel focus-panel"><div className="panel-title"><div><p className="eyebrow">FOCUS MODE</p><h2>جلسة تركيز</h2></div><span className="live-dot">جاهز</span></div><div className="focus-ring"><div><strong>{focusMinutes}:00</strong><small>دقيقة تركيز</small></div></div><div className="focus-actions"><button onClick={()=>setFocusMinutes(n=>n===25?50:25)}>تغيير المدة</button><button className="start">ابدأ الجلسة ▶</button></div></section>
   </div></section></main>
}

